### ISSUE TITLE
Add PhotoGIMP as a hyperlink in the Photoshop description 

### ISSUE THREAD

**Issue by domportera** [scholablade/Deadobe#6]
many people coming here will be familiar and proficient with adobe tools, I.e. Photoshop. [PhotoGIMP](https://github.com/Diolinux/PhotoGIMP) is an add-on for GIMP that makes it more accessible to people used to the Photoshop workflow and shortcuts. It's one of those things I wish I knew about a long time ago

**Comment by scholablade** [comment]
Done, I think? 
Please confirm.

**Comment by domportera** [comment]
ya that's just swell :) thanks!
